### ISSUE TITLE
Duplicate Instance of TestDriven.Net in System Tray

### ISSUE THREAD

**Issue by ayumsoftware** [jcansdale/TestDriven.Net-Issues#100]
I don't know if this is an alarming issue if I have 2 instances of of TestDriven.Net (or even more) in my system tray? Please see image attached.

This is just a theoretical example, so please bear with me :)

**TestRunner_1**
a) Run a test on an update method of my sample API
b) Code breaks and transaction (SQL transaction) is neither rolled back nor committed

_... and after a while, I run TestDriven.Net again (but this time, let's say it creates another instance "TestRunner_2")_

**TestRunner_2**
a) Using a dirty read or Read Uncommitted (I just use this to create the theoretical problem), I run again some tests

**Question:**
Will I not encounter a problem here since the first transaction run on "TestRunner_1" has not finished yet and I concurrently run another set of tests this time in another instance "TestRunner_2"?

This really might happen in real scenario. One time we stumble upon this problem but the good thing is, we were able to spot the problem and we explicitly rolled back our transaction if somewhere the test will throw an exception (thus leaving the transaction open). But my question is, do I need to worry in my future tests if this happens to me that there are multiple instances of TestDriven.Net runners?

@jcansdale 
P.S.
Thank you by the way for patiently explaining my ad-hoc problem on NUnit issue [#2238]. It helps me a lot to understand how TestDriven.Net works (or should work).

![testdriven](https://user-images.githubusercontent.com/29325852/27083850-7797f72a-507c-11e7-8b29-a7c326c98570.png)

**Comment by jcansdale** [comment]
Hi @ayumsoftware,

This might happen if you have test projects that target different version of .NET. Maybe you have one that targets .NET 3.5 and another that targets 4.0?
