### ISSUE TITLE
Install with VS 2017 "preview" band

### ISSUE THREAD

**Issue by ErikEJ** [jcansdale/TestDriven.Net-Issues#102]
Is it possible to install with the VS 2017 preview releases?

**Comment by pmiddleton** [comment]
I just tried installing in the latest VS 2017 preview and it won't install for me.  Hopefully support gets added soon.

**Comment by grokky1** [comment]
👍

**Comment by smitpatel** [comment]
See https://github.com/jcansdale/TestDriven.Net-Issues/issues/76#issuecomment-288583932

Its bit hacky but you can intall TestDriven in RTM version of VS and then copy the folder into preview version of VS and run those steps and it will light in VS preview.

**Comment by jcansdale** [comment]
Sorry I missed this issue. 😊  I'm glad you managed to get it working.

Thanks @smitpatel for pointing folks in the right direction!
