### ISSUE TITLE
Unable to install TestDriven.NET-4.1.3531_Personal_Beta (upgrade?)

### ISSUE THREAD

**Issue by propagated** [jcansdale/TestDriven.Net-Issues#112]
Hey Jamie, trying to install the latest beta in my dev VM (win10) with VS2017 community. I previously had VS2013 in this environment, which i uninstalled via the MS visual studio uninstaller. This may have wreaked havoc on your uninstaller because now i'm faced with this in the beta installer: 
![image](https://user-images.githubusercontent.com/3504728/39681955-20dc755e-517b-11e8-8b2c-5ffd9d73c846.png)

and this if i try to manually uninstall
![image](https://user-images.githubusercontent.com/3504728/39681961-28ae302e-517b-11e8-9771-8798a7e0e043.png)

Any advice? Big fan and i appreciate your continued maintenance of the project despite your new position.

**Comment by jcansdale** [comment]
Hi @propagated, thanks for your message. 😄 

Could you try uninstalling TestDriven.Net using this:
https://support.microsoft.com/en-ca/help/17588/fix-problems-that-block-programs-from-being-installed-or-removed

It's the modern equivalent of the now obsolete Msizap. It seems to deal with most stuck uninstalls. If all goes to plan, you should be able to install the new version. 🤞 

Let me know how you get on....

**Comment by propagated** [comment]
@jcansdale looks like that did the trick for the uninstall, and the install is successful. Closing this.

Any idea on roadmap for .net Core 2.x support?
