### ISSUE TITLE
RTM version for .NET Core

### ISSUE THREAD

**Issue by kkorus** [jcansdale/TestDriven.Net-Issues#114]
Is it know when we can expect RTM version for .NET Core?

**Comment by jcansdale** [comment]
@kkorus,

I'm afraid I don't know when I'll have an RTM version for .NET Core. I really want to get it working, especially now that .NET Core 3.0 been announced!

I now have a family and a full time job working on the GitHub Extension for Visual Studio. Things have been pretty manic around here...

Sorry about the delay and thanks for your patience!

**Comment by kkorus** [comment]
@jcansdale Thanks, just give us hope 😉
