### ISSUE TITLE
TestDriven.Net doesn't appear

### ISSUE THREAD

**Issue by gcastre** [jcansdale/TestDriven.Net-Issues#119]
Hello,

I used the TestDriven.NET-4.1.3531 setup but nothing happen in my Visual Studio (15.7.3)

The folder "TestDriven" is missing in \Common7\IDE\Extensions but the TestDriven folder is present in C:\Program Files (x86)\TestDriven.NET 4

Could it be because my Visual Studio is in the D: instead of C: ?

**Comment by jcansdale** [comment]
@gcastre,

> Could it be because my Visual Studio is in the D: instead of C: ?

Yes, this will be the problem. The MSI for TestDriven.Net only knows how to install itself into a few well known Visual Studio locations. I'm edging my way towards a pure VSIX installer where this will no longer be an issue.

Here is the latest VSIX build:
[TestDriven.VSPackage.zip](https://github.com/jcansdale/TestDriven.Net-Issues/files/2096042/TestDriven.VSPackage.zip)

You should find that most features and test runners work as expected. Please let me know if you notice anything missing!
