### ISSUE TITLE
Test with NCover not available with VSIX installer.

### ISSUE THREAD

**Issue by StevePy** [jcansdale/TestDriven.Net-Issues#135]
I suspect NCover 1.5.8 isn't included in the VSIX installer, but saw no mention of this in the release info. I installed NCover, but not sure if/how the VSIX installed TDD.Net can be pointed at it.

On a side note, more of an NCover issue but I'm curious if anyone had seen issues with NCover 1.5.8 and NUnit 3.10.x? When attempting to run tests with NUnit 3.10.0 and 3.10.1, NCover 1.5.8 coverage the tests fail with:
"System.InvalidProgramException : Common Language Runtime detected an invalid program."
Backtracking to NUnit 3.9.0 and the tests run with coverage.
I fear it's reached the breaking point where NUnit has diverged from what that old NCover build can still interpret. A pity if that is the case as I will miss its simplicity.

**Comment by jcansdale** [comment]
> On a side note, more of an NCover issue but I'm curious if anyone had seen issues with NCover 1.5.8 and NUnit 3.10.x? When attempting to run tests with NUnit 3.10.0 and 3.10.1, NCover 1.5.8 coverage the tests fail with: "System.InvalidProgramException : Common Language Runtime detected an invalid program."

I loved the old version of NCover + NCoverExplorer and kept it working as long as possible (with some hacks). Alas it was developed before .NET 4.0 was released. It's amazing that it works at all on .NET 4.x, but it does have some issues like the `InvalidProgramException` you're seeing.

If I ever get the time I'll migrate over to using `OpenCover`. Unfortunately NCover support is a dead end and I've tried to keep the VSIX installer version as lean and maintainable as possible.

> I suspect NCover 1.5.8 isn't included in the VSIX installer, but saw no mention of this in the release info. I installed NCover, but not sure if/how the VSIX installed TDD.Net can be pointed at it.

Thanks for pointing this out. I'll mention it in the notes.
