### ISSUE TITLE
"Extension Already installed"

### ISSUE THREAD

**Issue by sm-g** [jcansdale/TestDriven.Net-Issues#142]
In Tools>Extensions and Updates I see that there is new version of extension: CurrentVersion 4.1, NewVersion 4.3.18025. After i update it, I got "Extension Already installed".

VS: 15.8.7

**Comment by jcansdale** [comment]
This scenario is a little tricky. There will be test runners installed by the EXE/MSI, and test runners that come bundled with the VSIX. For example, the EXE/MSI install includes multiple NUnit test runners for legacy versions, but the VSIX only included a test runner for NUnit 3+. I'll need to make sure that people don't lose functionality if the install the VSIX version over the top of an EXE/MSI install (or if it automatically updates).

**Comment by jcansdale** [comment]
Hi @sm-g,

Here is a new VSIX installer that can be installed over the top of a VSIX install:
[TestDriven.VSPackage_InstallOverMsi.zip](https://github.com/jcansdale/TestDriven.Net-Issues/files/2546178/TestDriven.VSPackage_InstallOverMsi.zip)

This is from a different PR branch to the `ValueTuple` fix. It included a fix to prevent test runners from the VSIX and MSI from being considered twice (the version installed by the VSIX will be given priority).

You can see this fix working if you attempt to execute a class that doesn't use a known test framework. Previously you would have seen this:
![image](https://user-images.githubusercontent.com/11719160/47958011-07a58800-dfba-11e8-9ab5-6482a182f650.png)

In this version you should only see the warning message once. Could you give it a try and let me know if you notice any problems?

**Comment by sm-g** [comment]
Sorry for late response. I could not reproduce "a class that doesn't use a known test framework", so I just uninstall MSI and use VS "Extensions and updates" to install VSIX (just missed that in was two independent extensions).
