### ISSUE TITLE
Are custom ITestRunner supported on .NET Core?

### ISSUE THREAD

**Issue by plioi** [jcansdale/TestDriven.Net-Issues#154]
I see you've made a lot of progress on .NET Core support in TestDriven.NET. Much appreciated!

You may recall that my side project, the [Fixie test framework](https://github.com/fixie/fixie), took part in your original custom test framework hooks: including an assembly in the nuget package that implements your ITestRunner interface, and including a Fixie.dll.tdnet XML file which points you to the right such implementing dll/class name.

I think I have my local setup on the latest and greatest VS and TestDriven.NET, but it appears that I'm only experiencing the Ad Hoc runner.

Would you expect arbitrary ITestRunner implementations like mine to work still, or did they (understandably!) have to fall by the wayside when Microsoft changed things up so much with .NET Core? I'm happy to dig deeper on my side if you'd expect that to work already, but didn't want to invest the time if it's already known to be a cut feature.

**Comment by jcansdale** [comment]
Hey 👋  I've only just noticed your issue, sorry! 😊 

> or did they (understandably!) have to fall by the wayside when Microsoft changed things up so much with .NET Core?

Mostly this I'm afraid. 😢 It would be great if there was some kind of custom test runner support. I keep meaning to investigate this further!

**Comment by plioi** [comment]
No worries! Thanks for confirming.
