### ISSUE TITLE
'Test With > Performance' not working on Visual Studio 2013 Premium

### ISSUE THREAD

**Issue by jcansdale** [jcansdale/TestDriven.Net-Issues#22]
When I "Test With" -> "Performance" under TD.Net, I see the following:

```
Instrumenting: c:\users\jay.miller\documents\visual studio 2013\Projects\UnitTestProject1\UnitTestProject1\bin\Debug\UnitTestProject1.dll
"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Team Tools\Performance Tools\VSInstr.exe" "c:\users\...\documents\visual studio 2013\Projects\UnitTestProject1\UnitTestProject1\bin\Debug\UnitTestProject1.dll"
Failed with exit code: 4
```
![perf-calltree](https://cloud.githubusercontent.com/assets/11719160/17179643/da2c1320-5411-11e6-8710-7c8ad8c39b73.png)

Symbols aren't being loaded.

**Comment by jcansdale** [comment]
It looks like I was using the wrong COR_PROFILER Guid. I was using `{2CCFACEE-5E60-4734-8A98-181D93097CD9}` but `{B61B010D-1035-48A9-9833-32C2A2CDC294}` seems to be the one that works. I'm not sure if I should ever use the original one (maybe they're 32/64 bit?), but I'm going to change it to the one I know works.

JustMock has a bunch defined here:
https://github.com/telerik/JustMockLite/blob/master/Telerik.JustMock/Core/ClrProfilerSetupHelper.cs

**Comment by jcansdale** [comment]
Hi @tailsu,

I was wondering if you might be able to help me with a question about the Visual Studio 2013 profiler.  I noticed you added a couple of Guids to the JustMock project. Do you know why Visual Studio uses 2 Guids? Are they for 32 and 64-bit profiling perhaps? Thanks for any pointers! :)

**Comment by tailsu** [comment]
The GUID's for the 32 and 64-bit are the same. It might be a sampling-vs-tracing profiler thingy, or a memory profiler. I never quite found out. In the JustMock installation there's this file:

[Telerik.JustMock.Configuration.exe.config](https://gist.github.com/tailsu/ad2ae03d0260b8b5651a87f3acc118e9)

where the VSPerf GUIDs always come in pairs and one is simply called "alt":

```
<add product="Visual Studio 2013 Profiler" name="VSPerf 12" profilerGuid="2CCFACEE-5E60-4734-8A98-181D93097CD9"/>
<add product="Visual Studio 2013 Profiler" name="VSPerf 12 64-bit" is64bit="true" profilerGuid="2CCFACEE-5E60-4734-8A98-181D93097CD9"/>
<add product="Visual Studio 2013 Profiler" name="VSPerf 12 alt" profilerGuid="B61B010D-1035-48A9-9833-32C2A2CDC294"/>
<add product="Visual Studio 2013 Profiler" name="VSPerf 12 64-bit alt" is64bit="true" profilerGuid="B61B010D-1035-48A9-9833-32C2A2CDC294"/>
```

No difference pertaining to bitness. Both GUIDs point to `VSPERFCORPROF.DLL`.

Go figure :)

**Comment by jcansdale** [comment]
> The GUID's for the 32 and 64-bit are the same. It might be a sampling-vs-tracing profiler thingy, or a memory profiler.

Ah, that would make sense. When I added support for this, I wasn't able to install Visual Studio 2013 Premium. I took a punt and guessed wrong. Thanks for the info!
