### ISSUE TITLE
Exception was reported by .NET Core / .xproj test runner

### ISSUE THREAD

**Issue by jcansdale** [jcansdale/TestDriven.Net-Issues#25]
This is a placeholder issue that hasn't been reported yet! (it will be opened if it becomes a real issue)

If you see this, please let me know what happened and paste the contents of your 'project.json' file so I can hopefully diagnose the problem. If you're short of time, you can just send me a tweet.

Thanks!

http://twitter.com/jcansdale

**Comment by jcansdale** [comment]
To be opened if this becomes an issue!

**Comment by shibaev** [comment]
I got this error when trying to run tests for .NET Standard library with TestDriven.Net:

```
Something went wrong. :( You can visit the following location (in an external browser) for help resolving the issue:

Exception was reported by .NET Core / .xproj test runner #25
https://github.com/jcansdale/TestDriven.Net-Issues/issues/25

System.Exception: Couldn't find 'project.json' relative to: C:\...\netcoreapp2.0\Tests.dll
   at TestDriven.NetCore.TestRunner.ProjectCsproj.GetProjectPath(String path)
   at TestDriven.NetCore.TestRunner.ProjectCsproj.LoadForAssembly(String assemblyFile)
   at TestDriven.NetCore.TestRunner.NetCoreTestRunner.run(ITestListener testListener, String assemblyFile, String cref)
   at TestDriven.NetCore.TestRunner.NetCoreTestRunner.Run(ITestListener testListener, String assemblyFile, String cref)

Please do report this exception! (see above)
```

The test project does not use project.json. Defined like that:
```
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net46;netcoreapp2.0</TargetFrameworks>
...
```

Tests are run just fine:
1. By TestDriven.Net for net46 configuration
2. By Visual Studio Test Explorer for both net46 and netcoreapp2.0 configurations

I use Visual Studio 2019 16.2.4

**Comment by duncansmart** [comment]
I renamed the project node in Solution Explorer, which renames the csproj and started getting this error. I renamed it back and it works again. I thinking it's down to it needing to use the `AssemblyName` property in the csproj instead.

**UPDATE**: maybe not, getting same error today when trying to run an ad-hoc test.

**Comment by duncansmart** [comment]
Found the bug by debugging TestDriven.NetCore.TestRunner.dll using **dnSpy**. TL;DR is `ProjectCsproj.FindProjectPath` assumes the project directory is the same as the csproj name.

So in my case my project and assembly are called **PdfService** in a directory called **PdfServiceCore** in the location `C:\Foo\Bar\PdfServiceCore\PdfService.csproj`. 

So it first looks for:
1. `C:\Foo\Bar\PdfServiceCore\PdfServiceCore.csproj` and then 
2. `C:\Foo\Bar\Bar.csproj` ???

**Comment by jcansdale** [comment]
@duncansmart Thanks for doing the leg work on this and hat tip for your use of `dnSpy`! 😄 

In the bad old days of .xproj files, I needed to do some pretty perverse stuff to get .NET Core support working. For example, it was only possible to find the first target assembly from a multi-targeting .xproj project. If a .NET framework target was defined first, it wouldn't have been possible to execute a .NET Core target that was defined later.

This is why the code is searching for project files relative to the target assembly file. With a bit of guess work, is was just about possible to navigate from a targeted .NET assembly to a .NET Core assembly.

In Visual Studio 2019, it is now possible to find the target assembly assembly associated with the target framework drop down. This means the above hack should no longer be necessary. It appears some of the old code is still getting executed.

I'll clean it up and get out a fixed version.

**Comment by asteffes** [comment]
Visual Studio Community Edition 2019 v16.3.6
TestDriven.NET Personal v5.0.18119
Test project .NET version: dotnet core target: 4.7.2

```
------ Test started: Assembly: xxx.Integration.dll ------

Something went wrong. :( You can visit the following location (in an external browser) for help resolving the issue:

Exception was reported by .NET Core / .xproj test runner #25
https://github.com/jcansdale/TestDriven.Net-Issues/issues/25

System.Exception: Couldn't find assembly file at: c:\users\astef\appdata\local\microsoft\visualstudio\16.0_98838469\TestDriven.NetCore.AdHoc\bin\Debug\net35\TestDriven.NetCore.AdHoc.exe
   at TestDriven.NetCore.TestRunner.NetCoreTestRunner.getTestRunnerAssemblyFile(String devPath, String fileName)
   at TestDriven.NetCore.TestRunner.NetCoreTestRunner.<>c.<.cctor>b__25_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at TestDriven.NetCore.TestRunner.NetCoreTestRunner.createNetFrameworkStartInfo(String framework, String assemblyFile, String cref, String testRunner, Boolean debug)
   at TestDriven.NetCore.TestRunner.NetCoreTestRunner.run(ITestListener testListener, String assemblyFile, String cref)
   at TestDriven.NetCore.TestRunner.NetCoreTestRunner.Run(ITestListener testListener, String assemblyFile, String cref)

Please do report this exception! (see above)

```

**Comment by jcansdale** [comment]
Hi folks 👋 

Could you give this version a spin and let me know if the issue is resolved?
[TestDriven-5.0.18121-beta.zip](https://github.com/jcansdale/TestDriven.Net-Issues/files/3773555/TestDriven-5.0.18121-beta.zip)

**Comment by asteffes** [comment]
@jcansdale same error.

Thank you for your reply.

![image](https://user-images.githubusercontent.com/444194/67707531-a45df400-f988-11e9-92dc-58be3099cfef.png)


![image](https://user-images.githubusercontent.com/444194/67707617-cbb4c100-f988-11e9-81ac-cfc84404fa8b.png)

**Comment by jcansdale** [comment]
@asteffes any chance you could zip up a solution that repros this?

**Comment by asteffes** [comment]
I can't share the code that's creating this specific error. I will see if I can spin up a solution that recreates the same issue and send it your way. It won't happen anytime soon, though. 

Thanks for your help and feedback on this. I'll ping you when I have something.

**Comment by rhyland** [comment]
The zip file posted above does work with Visual Studio 2019.  Will look forward to the version that works with NET Core (without having to remove my XUnit [Fact] attributes.

Thanks for fixing.
