### ISSUE TITLE
Add support for targeting xUnit .NET Core generic types

### ISSUE THREAD

**Issue by jcansdale** [jcansdale/TestDriven.Net-Issues#26]
@bradwilson Do you know off hand what a generic type should look like when passed using `dotnet-test-xunit -class <generic-class>`. I'm guessing it isn't the same as `Type.FullName`?

**Comment by jcansdale** [comment]
On second thoughts, this might not actually be an issue. It looks like the base (abstract) class is generic, but the concrete classes are non-generic. If the test runner collects all of the derived classes when an abstract class is targeted, it's still only passing non-generic types to the xUnit runner. :)

**Comment by bradwilson** [comment]
Yeah, that's the answer: we don't support testing open generics. :)
