### ISSUE TITLE
Skip .xproj / project.json style projects that don't contain any tests

### ISSUE THREAD

**Issue by jcansdale** [jcansdale/TestDriven.Net-Issues#33]

**Comment by jcansdale** [comment]
Non-test projects are currently reported like this:

```
------ Test started: Assembly: XUnitTests.dll ------

xUnit.net .NET CLI test runner (64-bit .NET Core win10-x64)
hmmmm
Test 'XUnitTests.Program.Test2' failed: Assert.Equal() Failure
Expected: 4
Actual:   5
	at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer)
	Program.cs(25,0): at XUnitTests.Program.Test2()

1 passed, 1 failed, 0 skipped, took 2.07 seconds (netcoreapp1.0).

------ Test started: Assembly: ClassLibrary1.dll ------

Couldn't find an appropriate testRunner to execute your tests.
Please ensure your project is a Console Application and has one of the following as a dependency:
"dotnet-test-nunit"
"dotnet-test-xunit"

Alternatively, any method or property without a test attribute can be executed as an "Ad hoc" test.
```

@bradwilson Is this the issue you mentioned?

**Comment by jcansdale** [comment]
@bradwilson,

Could you give this build a try:
[TestDriven.NET-4.0.3347_Extraterrestrial_Alpha.zip](https://github.com/jcansdale/TestDriven.Net-Issues/files/404018/TestDriven.NET-4.0.3347_Extraterrestrial_Alpha.zip)

**Comment by bradwilson** [comment]
Nope, still not able to run tests. Trying to run an assembly gives me no output (just the 0/0/0 message in the status bar).

**Comment by bradwilson** [comment]
To be clear, these are desktop assemblies that are decorated with:

```csharp
[assembly: TestDriven.Framework.CustomTestRunner(typeof(Xunit.Runner.TdNet.TdNetRunner))]
```

**Comment by jcansdale** [comment]
Ah right, now I get it! It should be feasible to get this discovery mechanism working. In general NuGet makes runner discovery into a bit of a nightmare. Luckily this technique sidesteps the issue. :)

**Comment by jcansdale** [comment]
This issue needed to be sorted anyway, so I'm not upset I got confused. :wink: 

Here's an issue to track the issue you reported: #35.
