### ISSUE TITLE
Can't find .xproj assembly when project name is different to folder name

### ISSUE THREAD

**Issue by jcansdale** [jcansdale/TestDriven.Net-Issues#34]
@tillig wrote:

> On an .xproj + project.json style project... not so much.
> 
> I have a solution with two projects - "Identity" and "Identity.Test". The Identity project compiles to SilverLining.Application.Identity.dll; the test project compiles to SilverLining.Application.Identity.Test.dll.
> 
> When I try to run the tests - debugger, .NET Core, whatever runner - I get:
> 'C:\dev\sl\ui-identity\test\SilverLining.Application.Identity.Test\bin\Debug\net46\Identity.Test.dll' doesn't exist.
> Please ensure that the project has been compiled.
> 
> Note it's looking for the wrong assembly name. It can't find "Identity.Test.dll" because that's not the name of the assembly.

**Comment by jcansdale** [comment]
@tillig,

Could you give this build a try:
[TestDriven.NET-4.0.3347_Extraterrestrial_Alpha.zip](https://github.com/jcansdale/TestDriven.Net-Issues/files/404023/TestDriven.NET-4.0.3347_Extraterrestrial_Alpha.zip)

**Comment by tillig** [comment]
That works! Thanks!
