### ISSUE TITLE
Add support for testing 'Portable' Class Library projects

### ISSUE THREAD

**Issue by jcansdale** [jcansdale/TestDriven.Net-Issues#4]
This currently seems to work when running ad-hoc methods, but should also work with other runners (with a few tweaks).

For example, with xUnit, place the following TestDriven.Net configuration file:

```
<TestRunner>
  <FriendlyName>xUnit.net {0}.{1}.{2} build {3}</FriendlyName>
  <AssemblyPath>..\net45\xunit.runner.tdnet.dll</AssemblyPath>
  <TypeName>Xunit.Runner.TdNet.TdNetRunner</TypeName>
</TestRunner>

```

...in your solution's NuGet folder:
packages\xunit.extensibility.core.*\lib\netstandard1.0\

Paging, @bradwilson

**Comment by bradwilson** [comment]
Are you also planning to support `.xproj` projects?

**Comment by bradwilson** [comment]
You should be able to test this with `2.2.0-beta3-build3303` (or later), available on [MyGet](https://myget.org/gallery/xunit).

**Comment by jcansdale** [comment]
> Are you also planning to support .xproj projects?

Yes, absolutely. I have ad-hoc test methods working already. :)

> If so, how do I write my adapter to enable support for .NET Core?

I'm planing to piggyback off the "dotnet test" runner stuff. I'll need a way to discover the extra parameters that need to be passed (e.g. dotnet test -method Class.Method). I welcome suggestions about how to handle this. Maybe this could be in a file called 'dotnet-test-xunit.tdnet.json' (next to the runner assembly). Alternatively, there could be a setting inside 'dotnet-test-xunit.runtimeconfig.json' (to avoid clutter).

> You should be able to test this with 2.2.0-beta3-build3303 (or later), available on MyGet.

Excellent, I can confirm that it works!

Was there a reason you decided not to use the following:
`<AssemblyPath>..\net45\xunit.runner.tdnet.dll</AssemblyPath>`

It will get run inside the desktop CLR and I assume `xunit.runner.tdnet.dll` was built for desktop as well?

**Comment by bradwilson** [comment]
> I'm planing to piggyback off the "dotnet test" runner stuff.

I'm surprised. I expected you to ask people to code to your existing API, just with a .NET Core compatible API surface.

Given that you're doing that, you should look at the special hooks already required by the Visual Studio test runner, and see if you can reuse them. They are noted here:

https://github.com/xunit/dotnet-test-xunit/blob/765f506f598a88055705b5c49c9da71b50d900e4/src/dotnet-test-xunit/CommandLine.cs#L244-L282

**Comment by jcansdale** [comment]
I can confirm this works with xUnit 2.2.0-beta3. 👍 

Doesn't work with the latest NUnit. 😢
