### ISSUE TITLE
Add support for .NET Framework / .xproj based projects that use `ITestRunner` interface

### ISSUE THREAD

**Issue by jcansdale** [jcansdale/TestDriven.Net-Issues#40]
.NET Framework based projects should be able to work as they did before by simply referencing the test framework assembly (NUnit/xUnit/MSTest/etc). Only projects that target .NET Core should be required to use the new `dotnet test` / `testRunner` based test runners.

**Comment by jcansdale** [comment]
Tests will be executed using the original test runner interface when:

- There is no "testRunner" define in project.json.
- The first framework defined in "frameworks" is not .NET Core.

Otherwise both .NET Core and .NET Framework tests will be executed by the new "dotnet test" / "testRunner" interface. The `Test With > .NET Framework` and `Test With > .NET Core` commands will also use the new interface. This keeps testing as consistent as possible when testing using different frameworks.

**Comment by jcansdale** [comment]
Please give this build a try and let me know how you get on!

[TestDriven.NET-4.0.3348_Extraterrestrial_Alpha.zip](https://github.com/jcansdale/TestDriven.Net-Issues/files/407199/TestDriven.NET-4.0.3348_Extraterrestrial_Alpha.zip)

**Comment by bradwilson** [comment]
That appears to work for running methods, classes via source, and classes via Solution Explorer, but not assemblies or solutions. But getting closer! :)

**Comment by jcansdale** [comment]
Thanks for the catch. It's getting a bit ugly in places!

Could you give this one a try:
[TestDriven.NET-4.0.3349_Extraterrestrial_Alpha.zip](https://github.com/jcansdale/TestDriven.Net-Issues/files/407411/TestDriven.NET-4.0.3349_Extraterrestrial_Alpha.zip)

**Comment by bradwilson** [comment]
Victory!
