### ISSUE TITLE
Remove `Go To Code/Test` command

### ISSUE THREAD

**Issue by jcansdale** [jcansdale/TestDriven.Net-Issues#44]
NOTE: This command was rarely being used and taking up valuable space on the context menu.

There are better ways to do this these days and it takes up space on the code context menu.

**Comment by digitaldias** [comment]
Noooo!! This is sooooo useful!! put it back please!!

**Comment by jcansdale** [comment]
@digitaldias, I should have known you'd be out there! 😉 

The problem was the code wasn't pretty and its tests were written using TypeMock. Converting them over to NSubstitute for some functionality I no longer used was a bit daunting.

I'm happy to contribute the code if you'd like to use it as a separate extension. Luckily it's pretty standalone and doesn't use much (if any) TestDriven.Net code.

If you'd like to do this, just set up a repo and I'll send you a PR with a mini-extension (when I get the chance). Just think of a name and put something in the readme. I already have too many repos in my own GitHub account! 😉 

Here is the pertinent code.
[GoToAssociatedCodeCommandTarget.zip](https://github.com/jcansdale/TestDriven.Net-Issues/files/869939/GoToAssociatedCodeCommandTarget.zip)
(it's old and not very good, but it works)
