### ISSUE TITLE
Add support for running NUnit tests using .NET Core

### ISSUE THREAD

**Issue by jcansdale** [jcansdale/TestDriven.Net-Issues#6]

**Comment by jcansdale** [comment]
@rprouse, @CharliePoole,

I've finally got running NUnit tests running using .NET Core working quite well. It uses the `dotnet-test-nunit` assembly for test execution and consumes its events.

![netcore_nunit](https://cloud.githubusercontent.com/assets/11719160/16808141/2893203a-4913-11e6-8915-819b7dd32e15.png)

If a target method doesn't have any custom attributes, it will execute it as an ad-hoc test. I'm sure there are things we can do to speed up test execution. You can see the ad-hoc test below only took 0.37 seconds. For example, Microsoft.Extensions.Testing.Abstractions is pretty heavy for something that chucks out a bunch of JSON messages. :wink: 

![adhoc](https://cloud.githubusercontent.com/assets/11719160/16808343/0fba37b4-4914-11e6-9ecf-1a1b8a11c9e0.png)

Here's the installer if you fancy giving it a spin:

[TestDriven.NET-4.0.3264_Extraterrestrial_Alpha.zip](https://github.com/jcansdale/TestDriven.Net-Issues/files/361769/TestDriven.NET-4.0.3264_Extraterrestrial_Alpha.zip)

**Comment by rprouse** [comment]
Nice, I will give it a try when I have a few spare minutes. :+1:

**Comment by jcansdale** [comment]
@rprouse I had to make some tweaks to allow the development version of `dotnet.test.nunit` to run tests on itself (changes in the TestDriven.Net runner, not `dotnet.test.nunit` itself).

![nunit_dogfood](https://cloud.githubusercontent.com/assets/11719160/16843079/b6141ad0-49d7-11e6-90a0-238877bfe06d.png)

Here is an updated version that supports dogfooding:

[TestDriven.NET-4.0.3265_Extraterrestrial_Alpha.zip](https://github.com/jcansdale/TestDriven.Net-Issues/files/363985/TestDriven.NET-4.0.3265_Extraterrestrial_Alpha.zip) :rocket:

**Comment by rprouse** [comment]
@jcansdale that is pretty cool, I will definately find time to try it now :+1:

**Comment by jcansdale** [comment]
@rprouse I've just pushed a new version with debugger support etc. to the website:
http://testdriven.net/download.aspx
