### ISSUE TITLE
TD.NET in CI/CD

### ISSUE THREAD

**Issue by wahmedswl** [jcansdale/TestDriven.Net-Issues#62]
Hi, is there any support for TD.NET to be used with CLI. As, currently i am using xUnit for Testing and i want to get code coverage with TD.NET, is it possible?

Thanks

**Comment by jcansdale** [comment]
Hello,

TestDriven.Net is focused on running tests from inside Visual Studio. I'm afraid it doesn't support running with code coverage on a CI server.

Regards,
Jamie.
