### ISSUE TITLE
Test With > NUnit not working in 4.0 Beta 2

### ISSUE THREAD

**Issue by jcansdale** [jcansdale/TestDriven.Net-Issues#71]
NOTE: Restore option to test using the old NUnit 2.5.10 GUI from project context menu.

After upgrade to latest beta 2 version, in VS2015 if I right click a project and choose Test With - > Nunit, the nunit console GUI does not open, and I have no error. 
 
It worked like a charm before the upgrade, where should I look to troubleshoot this problem?
 
Thanks a lot in advance.

**Comment by jcansdale** [comment]
Almost certainly caused by this:

```
[16504] initing command: System.NullReferenceException: Object reference not set to an instance of an object. 
[16504]    at TestDriven.Services.Commands.GuiApplicationTarget..ctor(String applicationName, Utilities utilities) 
[16504]    at TestDriven.Services.Commands.GuiApplicationHandler.Create(Object parent, Object configContext, XmlNode section) 
[16504]    at MutantDesign.ManagedAddIns.Services.CommandsService.CommandComponent..ctor(DTE dte, AddIn addIn, BindingsStore bindingStore, Command commandSection) 
[16504]    at MutantDesign.ManagedAddIns.Services.CommandsService.AddNamedCommand(Command commandSection) 
[16504]    at MutantDesign.ManagedAddIns.Services.CommandsService.initNamedCommands(CommandsSection section) 
```

**Comment by jcansdale** [comment]
Could you give this build a try:
[TestDriven.NET-4.0.3438_Extraterrestrial_Beta2.zip](https://github.com/jcansdale/TestDriven.Net-Issues/files/581272/TestDriven.NET-4.0.3438_Extraterrestrial_Beta2.zip)

**Comment by alkampfergit** [comment]
Actually I have some problem uninstalling the actual version, I've launced the new installer, it tried to uninstall the actual beta2 version then it failed.

![image](https://cloud.githubusercontent.com/assets/358545/20182983/f4c93794-a763-11e6-8c58-03285ba005d5.png)

Then I decided to uninstall manually

![image](https://cloud.githubusercontent.com/assets/358545/20182995/ffb7ce5e-a763-11e6-957b-3b697922c298.png)

I got an error from VS2010 (I only have shell installed)
![image](https://cloud.githubusercontent.com/assets/358545/20183001/08ae9bc8-a764-11e6-8307-3a66669ee209.png)

Finally this error

![image](https://cloud.githubusercontent.com/assets/358545/20183007/0ec5c22a-a764-11e6-8a37-55b891838d9d.png)

I'll try after a reboot.

**Comment by jcansdale** [comment]
😢 

What happens if you just run the setup.exe?

**Comment by alkampfergit** [comment]
The very same error, with the old installer and the new installer, it seems that something got wrong in my installation :/

**Comment by jcansdale** [comment]
I wonder if you might have a borked install if .NET v1.1. Could you try renaming the following directory and having another go:
\Windows\Microsoft.NET\Framework\v1.1.4322
(this would force the TD.Net installer to used a different version of .NET)

It's a long shot, but worth a try...

**Comment by alkampfergit** [comment]
Pretty radical solution, but when I try to rename that folder the rename failed because the folder is in use.

**Comment by alkampfergit** [comment]
1. Fixed the uninstall problem with this microsoft fix (https://support.microsoft.com/en-ca/help/17588/fix-problems-that-block-programs-from-being-installed-or-removed)
2. installed this extraterrestial version
3. Problem is solved :) thanks.

**Comment by jcansdale** [comment]
> Pretty radical solution, but when I try to rename that folder the rename failed because the folder is in use.

It happens from time to time that .NET 1.1 is borked and people only notice when TestDriven.Net's installer doesn't work. I'm surprised you have something installed that's actively using .NET 1.1. 😄 

> Fixed the uninstall problem with this microsoft fix (https://support.microsoft.com/en-ca/help/17588/fix-problems-that-block-programs-from-being-installed-or-removed)

Thank you very much for the link, I'd never come across this before. In the past I've suggested (the no longer supported) Msizap.exe when someone's installer registry was corrupted. It's good to know there is an alternative and supported option!

Good to hear the problem is solved.

**Comment by alkampfergit** [comment]
Never heard of that link before, but the problem is somewhat due to some broken registry link for .msi package. That tool listed all application that are found to be installed in the registry, I just selected testdriven.net and it told me that there were a couple of error that were fixed, application uninstalled correctly and I was able to install again TestDriven.Net ;)
