### ISSUE TITLE
Can you put the .csproj context menu buttons back below "build" like in VS2012?

### ISSUE THREAD

**Issue by jcansdale** [jcansdale/TestDriven.Net-Issues#72]
NOTE: Project context menu buttons are now placed in consistent locations.

Pete Williams ‏@propagated
> @jcansdale huge fan of td, just installed the VS2015 version. can you put the .csproj contextmenu buttons back below "build" like in VS2012?

https://twitter.com/propagated/status/796476906803597312

![cw2ngljxuaad7bk](https://cloud.githubusercontent.com/assets/11719160/20159687/45bf6220-a6da-11e6-9614-0103bf304e61.jpg)

**Comment by jcansdale** [comment]
@propagated,

I'll try! I think there was some reason I didn't when I converted TestDriven.Net from being an add-in to package (on VS 2015). I'll have another go though. 😄

**Comment by jcansdale** [comment]
You'd never guess what a pain getting menu buttons in the right place could be! It's complete trial and error and even people who've been writing Visual Studio extensions for years don't know a good way to do it. Madness! Anyway, thanks for prompting me to have another go. 😄 

Could you give this build a spin:
[TestDriven.NET-4.0.3439_Extraterrestrial_Beta2.zip](https://github.com/jcansdale/TestDriven.Net-Issues/files/586624/TestDriven.NET-4.0.3439_Extraterrestrial_Beta2.zip)

**Comment by propagated** [comment]
giving it a spin now. FYI on uninstall i was prompted to reboot, but it didn't matter. Interestingly enough i was not prompted to restart my VS2015 but i did anyway so i don't know if the changes happened live. In either case:

![image](https://cloud.githubusercontent.com/assets/3504728/20231914/e218d3d2-a832-11e6-8e70-4d44b1b35636.png)
 Awesome! appears to be working

**Comment by jcansdale** [comment]
> FYI on uninstall i was prompted to reboot, but it didn't matter.

I've tweaked and (mostly) improved the installer over the years, but it still throws up the odd unexpected thing!

Excellent, glad t hear it's working. Let me know if you notice anything else! 😄

**Comment by propagated** [comment]
I do know the woes of the installer. Gonna start experimenting with docker soon. 

My muscle memory thanks you for the button shuffle!
