### ISSUE TITLE
Doesn't run with netcoreapp1.1

### ISSUE THREAD

**Issue by denisz1** [jcansdale/TestDriven.Net-Issues#75]
My test project's `project.json`:

    {
      "version": "1.0.0-*",
      "dependencies": {
        "MyProject": { "version": "1.0.0-*", "target": "project" },
        "NUnit": "3.5.0",
        "dotnet-test-nunit": "3.4.0-beta-2"
      },
      "frameworks": {
        "netcoreapp1.1": {
          "dependencies": {
            "Microsoft.NETCore.App": { "version": "1.1.0", "type": "platform" }
          },
          "imports": [ "portable-net45+win8" ]
        }
      },
      "testRunner": "nunit"
    }

Output in VS2015 when I try to use TestDriven.Net to run some test:

    ------ Test started: Assembly: MyProject.Tests.dll ------

    NUnit .NET Core Runner 3.4.0 
    Copyright (C) 2016 Charlie Poole

    Could not load file or assembly 'Microsoft.DotNet.InternalAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

It works if I add that assembly, but never needed to do that before. And it compiles fine, so I'm not missing anything. I don't understand the problem here.

**Comment by jcansdale** [comment]
@denisz1 Sorry about the delay. It has been a crazy week. 😄 

Thanks for the report. It isn't immediately obvious why this isn't working. I'll investigate and get back to you.

Out of interest, are there any bad side effects when you add `Microsoft.DotNet.InternalAbstractions`? I'm wondering if this could be done automatically (without actually modifying the project).

**Comment by denisz1** [comment]
@jcansdale Nope it seems to work fine, and there are no side-effects that I can see (yet). The automatic option would be great.

**Comment by jcansdale** [comment]
That's good to know. I'll ping you again when it's working.

**Comment by slorion** [comment]
Hello,

Is there any update on this issue ? I am using VS 2017 RTM with .NET Core 1.1 and xUnit 2.2.0 and I get the same error 

`Could not load file or assembly 'xunit.abstractions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' or one of its dependencies. The system cannot find the file specified.`

I cannot add this specific version because it is not compatible with .NET Core 1.1 and adding the latest version does not solve the issue.

**Comment by duncanawoods** [comment]
@jcansdale Any news when testdriven.net will support .Net core on VS2017?

**Comment by jcansdale** [comment]
@slorion, @duncanawoods, @denisz1 I've _finally_ .NET Core support working with Visual Studio 2017 (just running ad-hoc methods for the moment). You can find an experimental build here https://github.com/jcansdale/TestDriven.Net-Issues/issues/106#issuecomment-452926516.

I'll be tracking .NET Core support in #106, so closing this issue.
