### ISSUE TITLE
Add support for Visual Studio 2017 RC

### ISSUE THREAD

**Issue by jcansdale** [jcansdale/TestDriven.Net-Issues#76]
NOTE: TestDriven.Net will be installed for Visual Studio 2017 RC (Community, Professional and Enterprise in their default locations).

Workaround:

The following BAT file must be run as admin user. Change VS2017SKU to "Community", "Professional" or "Enterprise" (depending on which Visual Studio 2017 SKU you have installed).

```
set VS2017SKU=Community
set VS2017IDE=%ProgramFiles(x86)%\Microsoft Visual Studio\2017\%VS2017SKU%\Common7\IDE
set VS14IDE=%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\Common7\IDE
set TDEXT=Extensions\TestDriven
xcopy /S /I "%VS14IDE%\%TDEXT%" "%VS2017IDE%\%TDEXT%"
"%VS2017IDE%\devenv.exe" /updateConfiguration
```

Please subscribe to this issue for updates!

**Comment by jcouv** [comment]
Thanks a lot. That worked.

I ran the command with a small modification on the last line:
```
set VS2017SKU=Enterprise
set VS2017IDE=%ProgramFiles(x86)%\Microsoft Visual Studio\2017\%VS2017SKU%\Common7\IDE
set VS14IDE=%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\Common7\IDE
set TDEXT=Extensions\TestDriven
xcopy /S /I "%VS14IDE%\%TDEXT%" "%VS2017IDE%\%TDEXT%"
"%VS2017IDE%\devenv.exe" /updateConfiguration
```

**Comment by jcansdale** [comment]
Oops, thanks for the fix! I've updated it above. I'm glad it worked (apart than that 😊).

**Comment by jcouv** [comment]
In case anybody is having the same problem with the preview channel of VS2017, here's the same script to copy from VS2017 to VS2017 Preview:

```
set VS2017SKU=Enterprise
set VS2017IDE=%ProgramFiles(x86)%\Microsoft Visual Studio\2017\%VS2017SKU%\Common7\IDE
set VS2017PreviewIDE=%ProgramFiles(x86)%\Microsoft Visual Studio\Preview\%VS2017SKU%\Common7\IDE
set TDEXT=Extensions\TestDriven
xcopy /S /I "%VS2017IDE%\%TDEXT%" "%VS2017PreviewIDE%\%TDEXT%"
"%VS2017PreviewIDE%\devenv.exe" /updateConfiguration
```

**Comment by jcansdale** [comment]
@jcouv, thanks for the info!  I didn't know about the preview channel. 😕 

Is this it here?
https://www.visualstudio.com/en-us/news/releasenotes/vs2017-preview-relnotes

I was interested to find a Team Explorer standalone install.

**Comment by jcouv** [comment]
That looks like it, but I'm not sure. The installer (linked from the page you mentioned) installs in the same path as the installer I used (ie `C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise`).

**Comment by kzu** [comment]
The workaround worked great for me too!
