### ISSUE TITLE
Please re-introduce "Navigate to test or code" 

### ISSUE THREAD

**Issue by digitaldias** [jcansdale/TestDriven.Net-Issues#88]
This my most important reason for using TestDriven.Net. If all else fails, I wouldn't care, but this one is a serious must-have. 

Perhaps there are alternatives that do the same? If so, could you share them?

**Comment by jcansdale** [comment]
Hello @digitaldias,

By popular demand I'm restoring the "Navigate to test or code" command. The command is called `TestDriven.NET.GoToTestOrCode` and you assign a shortcut to that.

![image](https://cloud.githubusercontent.com/assets/11719160/25783056/7ceb4bec-334d-11e7-9fff-e8b3a0a049ae.png)

You can find a build with is restored here:
[TestDriven.NET-4.0.0_Extraterrestrial_Beta3.zip](https://github.com/jcansdale/TestDriven.Net-Issues/files/981757/TestDriven.NET-4.0.0_Extraterrestrial_Beta3.zip)

I felt like I was being greedy and adding too many buttons to the code context menu. The underlying command is now restored, but I haven't put it back on the code context menu. I hope that isn't a problem!

Cheers,
Jamie.

**Comment by jcansdale** [comment]
Fixed in https://github.com/jcansdale/TestDriven.Net/pull/28
